SUPABASE_URL = "https://yohuytxulwzgvthpaoiq.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvaHV5dHh1bHd6Z3Z0aHBhb2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MzIzNzMsImV4cCI6MjA3NzUwODM3M30.Ax6ymwDOWeWoxmbeodpew_NHTnlQlW4HPgiBbvjlSmE"
